name: CI for CBA COVID19 Game

on: [push]

jobs:
  
  api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: npm install and test APIs
        run: |
          npm install
          npm test api_tests
  
  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: npm install and test UI
        run: |
          npm install
          npm test frontend_tests